FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN mkdir /code

WORKDIR /code
COPY . /code/

RUN pip install pipenv
ADD Pipfile /code/
RUN pipenv install --system

RUN adduser --disabled-login project
USER project
