FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN mkdir /code

WORKDIR /code
COPY . /code/

RUN pip install poetry
RUN poetry config virtualenvs.create false
ADD poetry.lock pyproject.toml /code/
RUN poetry install --no-dev

# This is needed only if we don't use S3 to store staticfiles
RUN python manage.py collectstatic --noinput

RUN adduser --disabled-login project
USER project
