name: Danger

on: [pull_request]

jobs:
  danger:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: Installing danger, code-coverage and jira-danger
        run: |
          npm init --yes
          npm install danger danger-plugin-istanbul-coverage danger-plugin-jira-issue --dev

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
          architecture: "x64"

      - name: Set up poetry
        run: |
          pip3 install poetry
          poetry config virtualenvs.create true
          poetry config cache-dir

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: poetry-${{ runner.os }}-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            poetry-${{ runner.os }}-

      - name: Install deps
        run: poetry install

      - name: Run pylint
        run: poetry run pylint project/ --rcfile=.pylintrc >> pylint.json
        continue-on-error: true

      - name: Danger
        run: npx danger ci
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.TNP_GITHUB_TOKEN }}
